name: "Playwright tests with docker-compose"

on: push

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout to tests repository"
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'
          ref: ${{ github.ref }}
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2' # the full version of `docker-compose` command
      - name: "Run tests"
        env:
          ENV: 'dev'
          HTTP_CREDENTIALS_USERNAME: ${{ secrets.HTTP_CREDENTIALS_USERNAME }}
          HTTP_CREDENTIALS_PASSWORD: ${{ secrets.HTTP_CREDENTIALS_PASSWORD }}
        run: |
          docker-compose up --exit-code-from pw-tests
      - name: "Upload report to artifacts"
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ci-report
          path: playwright-report/
          retention-days: 3


